### PR TITLE
Add serde feature

### PR DESCRIPTION
**Pull request by manglemix**
Hi, your crate has been very useful to me and my robotics club. There is just one feature we needed and that is `serde` implementations. I've added it as an optional feature, and updated the readme.

### CODE REVIEW

**Comment by HamaguRe** [comment]
Hi, manglemix. Thank you for using this crate and for your proposal!

Regarding this crate, I haven't personally used it in a way that requires `serde`. What capabilities or conveniences would be unlocked by implementing this feature? (Like using it for logging?)

If it would be useful for many people, I would be happy to incorporate it.

**Comment by manglemix** [comment]
In my robotics club, I am writing a forward kinematics library where the rig can be defined using toml. When users describe the rotation of a bone, they will use euler angles. Just for extra clarity and assurance, I want to allow users to also specify the rotation order and type, just in case they find some other style besides YXZ and intrinsic to be more intuitive. The simplest way to do this would to just implement the serde traits for `RotationType` and `RotationSequence`. For now, I've just copied these enums and redefined them with the serde traits, and defined conversion methods to convert between my types and `quaternion-core` types.

**Comment by HamaguRe** [comment]
Ok, since the changes are few and optional, I'll take your proposal as is.
Have you confirmed that it works as desired with the changes?

**Comment by manglemix** [comment]
Yes it does work as intended

**Comment by HamaguRe** [comment]
Published as [version 0.5.0](https://crates.io/crates/quaternion-core/0.5.0) in crates.io.

**Pull request merged**
